import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';

class LocalizationService extends Translations {
  // 🔥 Default locale
  static final locale = const Locale('en', 'US');

  static final _box = GetStorage();
  static const String _storageKey = 'language_code';

  // 🔥 Fallback locale ถ้าไม่เจอภาษา
  static final fallbackLocale = const Locale('en', 'US');

  final currentLocale = const Locale('en', 'US').obs;

  // 🔥 ภาษาที่รองรับ
  static final langs = ['ไทย', 'English'];

  static final locales = [const Locale('th', 'TH'), const Locale('en', 'US')];

  @override
  Map<String, Map<String, String>> get keys => {
    'th_TH': {
      'hello,': 'สวัสดี',
      'login': 'เข้าสู่ระบบ',
      'logout': 'ออกจากระบบ',
      'cancel': 'ยกเลิก',
      'confirm': 'ยืนยัน',
      'register': 'สมัครสมาชิก',
      'email': 'อีเมล',
      'ai-import': 'สร้างงานด้วย AI',
      'analytics': 'การวิเคราะห์',
      'password': 'รหัสผ่าน',
      'todaytasks': 'งานวันนี้',
      'taskincoming(3days)': 'งานที่กำลังจะมาถึง (3 วัน)',
      'taskoverdue': 'งานที่เกินกำหนด',
      'confirmlogout': 'คุณต้องการออกจากระบบหรือไม่?',
      'dashboard': 'แดชบอร์ด',
      'notasksfortoday': 'ไม่มีงานสำหรับวันนี้ 🤙🏽',
      'noupcomingtasks': 'ไม่มีงานที่กำลังจะมาถึง',
      'nooverduetasks': 'ไม่มีงานค้าง',
      'tasklist': 'รายการงาน',
      'all': 'ทั้งหมด',
      'pending': 'รอดำเนินการ',
      'inprogress': 'กำลังทำ',
      'completed': 'เสร็จสิ้น',
      'overdue': 'งานค้าง',
      'loading': 'กำลังโหลดข้อมูล...',
      'notasksinthislist': 'ไม่มีงานในหมวดนี้',
      'startcreatetask': 'เริ่มสร้างงานใหม่กันเถอะ!',
      'addtask': 'เพิ่มงานใหม่',
      'startdate': 'วันที่เริ่มต้น',
      'duedate': 'วันที่ครบกำหนด',
      'out of date': 'เกินกำหนดแล้ว',
      'starttask': 'เริ่มงาน',
      'endtask': 'สิ้นสุดงาน',
      'deletetask': 'ลบงาน',
      'confirmchangestatus': 'ยืนยันการเปลี่ยนสถานะ',
      'dialogconfirmstatus': 'คุณต้องการเปลี่ยนสถานะงาน เป็นเสร็จแล้ว หรือไม่?',
      'comfirmdelete': 'ยืนยันการลบงาน',
      'dialogconfirmdelete': 'คุณแน่ใจว่าต้องการลบงาน หรือไม่?',
      'addnewtask': 'เพิ่มงานใหม่',
      'taskdetails': 'แก้ไขรายละเอียดงาน',
      'taskname': 'ชื่องาน',
      'settings': 'การตั้งค่า',
      'priority': 'ความสำคัญ',
      'low': 'ต่ำ',
      'status': 'สถานะ',
      'medium': 'ปานกลาง',
      'high': 'สูง',
      'subtasks': 'งานย่อย',
      'list_item': '@count รายการ',
      'add': 'เพิ่ม',
      'nosubtasks': 'ยังไม่มีงานย่อย',
      'guidelinessubtasks': 'แตะปุ่ม "เพิ่ม" เพื่อเพิ่มงานย่อย',
      'savetask': 'บันทึกงาน',
      'confirmdeletesubtask': 'คุณต้องการลบงานย่อยนี้หรือไม่?',
      'delete': 'ลบ',
      'hintnametask': 'กรอกชื่อของงานที่ต้องการทำ',
      'inserttaskname': 'กรุณากรอกชื่อของงาน',
      'subtaskname': 'ชื่องานย่อย',
      'subtaskdetails': 'รายละเอียดงานย่อย (ไม่จำเป็น)',
      'saving...': 'กำลังบันทึก...',
      'ai-task-manager': 'ตัวช่วยการจัดการงาน',
      "subtask_progress": "เสร็จแล้ว @completed จาก @total งาน",
      'addsubtask': 'เพิ่มงานย่อย',
      'deletesubtask': 'ลบงานย่อย',
      'entertaskname': 'กรุณากรอกชื่องาน',
      'tasksaved': 'บันทึกงานเรียบร้อยแล้ว',
      'cannotsave': 'ไม่สามารถบันทึกงานได้',
      'save': 'บันทึก',
      'insertname': 'ใส่ชื่องาน...',
      'date': 'ช่วงเวลา',
      "account": "บัญชีผู้ใช้",
      "support": "การสนับสนุน",
      "other_settings": "การตั้งค่าอื่นๆ",
      "profile_info": "ข้อมูลส่วนตัว",
      "profile_info_sub": "จัดการข้อมูลโปรไฟล์ของคุณ",
      "change_password": "เปลี่ยนรหัสผ่าน",
      "change_password_sub": "อัปเดตรหัสผ่านเพื่อความปลอดภัย",
      "logout_sub": "ออกจากบัญชีผู้ใช้ปัจจุบัน",
      "contact_support": "ติดต่อฝ่ายสนับสนุน",
      "contact_support_sub": "ได้รับความช่วยเหลือและแก้ไขปัญหา",
      "about_app": "เกี่ยวกับแอป",
      "about_app_sub": "ข้อมูลเวอร์ชันและนโยบาย",
      "notifications": "การแจ้งเตือน",
      "notifications_sub": "จัดการการแจ้งเตือนแอป",
      "language": "ภาษา",
      'languageheader': 'เลือกภาษา',
      "language_sub": "เลือกภาษาที่ต้องการใช้",
      "logout_title": "ออกจากระบบ",
      "logout_message": "คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ?",
      "confirm_logout": "ออกจากระบบ",
      "secure_account": "ปกป้องบัญชีของคุณ",
      "secure_account_desc": "อัปเดตรหัสผ่านเพื่อความปลอดภัยของบัญชี",
      "current_password": "รหัสผ่านปัจจุบัน",
      "current_password_hint": "กรอกรหัสผ่านปัจจุบันของคุณ",
      "current_password_error": "กรุณากรอกรหัสผ่านปัจจุบัน",
      "new_password": "รหัสผ่านใหม่",
      "new_password_hint": "กรอกรหัสผ่านใหม่ของคุณ",
      "new_password_error": "รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร",
      "confirm_new_password": "ยืนยันรหัสผ่านใหม่",
      "confirm_new_password_hint": "กรอกรหัสผ่านใหม่อีกครั้ง",
      "confirm_password_error": "รหัสผ่านไม่ตรงกัน",
      "password_tips": "เคล็ดลับการตั้งรหัสผ่าน",
      "tip_length": "ใช้ความยาวอย่างน้อย 8 ตัวอักษร",
      "tip_symbols": "ใส่ตัวเลขและสัญลักษณ์",
      "tip_case": "ผสมตัวพิมพ์เล็กและพิมพ์ใหญ่",
      "update_password": "อัปเดตรหัสผ่าน",
      'version': 'เวอร์ชัน : 1.0.0',
      'about_app_desc':
          'แอปนี้จะช่วยคุณจัดการงาน ติดตามความคืบหน้า และวิเคราะห์ประสิทธิภาพด้วยข้อมูลเชิงลึกที่ขับเคลื่อนด้วย AI.',
      'edit': 'แก้ไข',
      'overview': 'สถานะงานทั้งหมด',
      'tsakstatusoverview': 'เปอร์เซ็นจำนวนงานแต่ละสถานะ',
      'tasksbystatus': 'ชาร์ทจำนวนงานแต่ละสถานะ',
      'tasksNeedAttention': 'มี @count งานที่ต้องจัดการด่วน',
      'loginTitle': 'เข้าสู่ระบบ',
      'testUser1': 'ผู้ใช้ทดสอบ 1',
      'testUser2': 'ผู้ใช้ทดสอบ 2',
      'noAccount': 'ยังไม่มีบัญชี? ',
      'chooseLanguage': 'เลือกภาษา',
      'languageChanged': 'เปลี่ยนภาษาเป็น {lang} แล้ว',
      'profiledetails': 'จัดการโปรไฟล์',
      'subTitleTaskList': 'จัดการงานของคุณอย่างมีประสิทธิภาพ',
      "aiTaskGenerator": "AI Task Generator",
      "aiTaskGeneratorSubtitle":
          "แปลงข้อความเป็น Task พร้อม Sub-tasks อัตโนมัติ",
      "textToConvert": "ข้อความที่ต้องการแปลง",
      "pasteTextPlaceholder":
          "วางข้อความประชุม, อีเมล, หรือโน้ตที่ต้องการแปลงเป็น Task...",
      "processingWithAI": "กำลังประมวลผลด้วย AI...",
      "generateWithAI": "สร้าง Task ด้วย AI",
      "mainTaskInfo": "ข้อมูล Task หลัก",
      "taskName": "ชื่อ Task",
      "setMainTaskName": "กำหนดชื่อ Task หลัก",
      "start": "เริ่ม",
      "end": "สิ้นสุด",
      "subtask": "Sub-task",
      "noTaskName": "ไม่มีชื่อ Task",
      "noDetails": "ไม่มีรายละเอียด",
      "subtasksAppearHere": "Sub-tasks จะแสดงที่นี่",
      "typeAndGenerate": "ใส่ข้อความแล้วกดสร้าง Task",
      "saveMainTask": "บันทึก Task หลัก",
      "pleaseEnterText": "กรุณาใส่ข้อความ",
      "noSubtasksFound": "ไม่พบ Sub-tasks ที่สามารถแปลงได้",
      "aiError": "เกิดข้อผิดพลาดจาก AI",
      "pleaseEnterMainTaskName": "กรุณาใส่ชื่อ Task หลัก",
      "cannotSaveTask": "ไม่สามารถบันทึก Task ได้",
      "savedMainTaskWithNSubtasks":
          "บันทึก Task หลักพร้อม {{count}} รายการย่อยเรียบร้อยแล้ว ✓",
      'createyourtask': 'สร้าง Task ของคุณ',    
      "jan": "ม.ค.",
      "feb": "ก.พ.",
      "mar": "มี.ค.",
      "apr": "เม.ย.",
      "may": "พ.ค.",
      "jun": "มิ.ย.",
      "jul": "ก.ค.",
      "aug": "ส.ค.",
      "sep": "ก.ย.",
      "oct": "ต.ค.",
      "nov": "พ.ย.",
      "dec": "ธ.ค.",
      'form_info_text':
          'ความคิดเห็นของคุณช่วยให้เราปรับปรุงแอปและมอบประสบการณ์ที่ดียิ่งขึ้น',
      'taskview': 'ดูรายละเอียดงาน',
      'welcometext':
          'ยินดีต้อนรับสู่ AI Task Manager! จัดระเบียบงานของคุณอย่างมีประสิทธิภาพและเพิ่มผลผลิตของคุณด้วยคุณสมบัติที่ขับเคลื่อนด้วย AI ของเรา.',
      'total': 'รวมทั้งสิ้น',
      'selectLanguage': 'เลือกภาษาที่คุณต้องการ',
      'languageDescription': 'เลือกภาษาสำหรับหน้าจอของแอปพลิเคชัน',
      'apply': 'ตกลง',
      'currentLanguage': 'ภาษาปัจจุบัน',
      'active': 'ใช้งานอยู่',
      'ready-to-be-productive': 'พร้อมทำงานได้อย่างมีประสิทธิภาพ',
      'good-morning': 'สวัสดีตอนเช้า',
      'good-afternoon': 'สวัสดีตอนบ่าย',
      'good-evening': 'สวัสดีตอนเย็น',
      'active-tasks': 'งานที่กำลังทำ',
      'completion-rate': 'อัตราการสำเร็จ',
      'streak-days': 'จำนวนวันต่อเนื่อง',
      'view-overview': 'ดูภาพรวม',
      'manage-tasks': 'จัดการงาน',
      'ai-assistance': 'ช่วยเหลือ AI',
      'track-progress': 'ติดตามความคืบหน้า',
      'trackProgress': 'ติดตามความคืบหน้าของคุณ',
      'today': 'วันนี้',
      'thisWeek': 'สัปดาห์นี้',
      'thisMonth': 'เดือนนี้',
      'allTime': 'ทั้งหมด',
      'noDataYet': 'ยังไม่มีข้อมูล',
      'createTasksToSeeAnalytics': 'สร้างงานเพื่อดูการวิเคราะห์',
      'allTasks': 'งานทั้งหมด',
      'inProgress': 'กำลังดำเนินการ',
      'urgent': 'เร่งด่วน',
      'now': 'ตอนนี้',
      'performance': 'ประสิทธิภาพ',
      'productivity': 'ประสิทธิผล',
      'onTimeRate': 'อัตราการทำงานตรงเวลา',
      'taskDistribution': 'การกระจายงาน',
      'weeklyTrend': 'แนวโน้มรายสัปดาห์',
      'insights': 'ข้อมูลเชิงลึก',
      'noInsightsYet': 'ยังไม่มีข้อมูลเชิงลึก',
      'excellentWork': 'ผลงานยอดเยี่ยม!',
      'keepUpGoodWork': 'ทำต่อไปเช่นนี้! ประสิทธิผลของคุณยอดเยี่ยม',
      'goodProgress': 'ความก้าวหน้าดี',
      'roomForImprovement': 'คุณทำได้ดีแต่ยังมีที่พัฒนาได้อีก',
      'needsFocus': 'ต้องมีสมาธิ',
      'tryToCompleteMore': 'ลองทำงานให้เสร็จมากขึ้นเพื่อเพิ่มประสิทธิผล',
      'overdueTasks': 'งานเกินกำหนด',
      'focusTip': 'เทคนิคการมีสมาธิ',
      'considerFewTasks': 'ลองมุ่งเน้นงานน้อยชิ้นในเวลาเดียวกัน',
      'highActivity': 'กิจกรรมสูง',
      'veryProductive': 'คุณมีประสิทธิผลสูงมากในสัปดาห์นี้!',
      'warning': 'เตือน!',
      'appName': 'ผู้ช่วยจัดการงานด้วย AI',
      'appSubtitle': 'ฉลาด ใช้ง่าย มีประสิทธิภาพ',
      'initializing': 'กำลังเริ่มต้น...',
      'createAccountHeader': 'สร้างบัญชีผู้ใช้',
      'registerTitle': 'ลงทะเบียน',
      'fullName': 'ชื่อ-นามสกุล',
      'registerButton': 'ลงทะเบียน',
      'alreadyHaveAccount': 'มีบัญชีอยู่แล้ว? ',
      'backToLogin': 'กลับไปหน้าเข้าสู่ระบบ',
      'hiUser': 'สวัสดี, @name 👋',
      'displayname': 'ชื่อผู้ใช้',
      'chooseAvatar': 'เปลี่ยนรูปโปรไฟล์',
    },
    'en_US': {
      'hello,': 'Hello,',
      'login': 'Login',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'register': 'Register',
      'delete': 'Delete',
      'email': 'Email',
      'ai-import': 'AI-Import',
      'analytics': 'Analytics',
      'ai-task-manager': 'AI Task Management',
      'password': 'Password',
      'todaytasks': 'Today Tasks',
      'taskincoming(3days)': 'Upcoming Tasks (3 Days)',
      'taskoverdue': 'Overdue Tasks',
      'confirmlogout': 'Are you sure you want to log out?',
      'dashboard': 'Dashboard',
      'notasksfortoday': 'No tasks for today 🤙🏽',
      'noupcomingtasks': 'No upcoming tasks',
      'nooverduetasks': 'No overdue tasks',
      'tasklist': 'Task List',
      'all': 'All',
      'pending': 'Pending',
      'inprogress': 'In Progress',
      'completed': 'Done',
      'overdue': 'Overdue',
      'loading': 'Loading data...',
      'notasksinthislist': 'No Tasks In This List',
      'startcreatetask': 'Let\'s start creating a new task!',
      'addtask': 'Add New Task',
      'startdate': 'Start Date',
      'duedate': 'Due Date',
      'out of date': 'Out of Date',
      'starttask': 'In Progress',
      'endtask': 'DONE',
      'deletetask': 'Delete Task',
      'confirmchangestatus': 'Confirm Status',
      'dialogconfirmstatus': 'Do you want to change the task status to Done?',
      'comfirmdelete': 'Confirm Deletion',
      'dialogconfirmdelete': 'Are you sure you want to delete this task?',
      'addnewtask': 'Add New Task',
      'taskdetails': 'Edit Task Details',
      'taskname': 'Task Name',
      'settings': 'Settings',
      'priority': 'Priority',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'subtasks': 'Subtasks',
      'list_item': '@count List',
      'add': 'Add',
      'nosubtasks': 'No subtasks yet',
      'guidelinessubtasks': 'Tap "Add" to create a subtask',
      'savetask': 'Save Task',
      'confirmdeletesubtask': 'Do you want to delete this subtask?',
      'hintnametask': 'Enter the name of the task you want to create',
      'inserttaskname': 'Please enter the name of the task',
      'subtaskname': 'Subtask Name',
      'subtaskdetails': 'Subtask Details (Optional)',
      'saving...': 'Saving...',
      'entertaskname': 'Please enter task name',
      'tasksaved': 'Task saved successfully',
      'cannotsave': 'Cannot save task',
      'save': 'Save',
      'insertname': 'Enter task name...',
      'date': 'Date',
      'subtask_progress': 'Completed @completed of @total tasks',
      'addsubtask': 'Add Subtask',
      'deletesubtask': 'Delete Subtask',
      "account": "Account",
      "support": "Support",
      "other_settings": "Other Settings",
      "profile_info": "Profile Information",
      "profile_info_sub": "Manage your profile details",
      "change_password": "Change Password",
      "change_password_sub": "Update your password for security",
      "logout_sub": "Sign out of your current account",
      "contact_support": "Contact Support",
      "contact_support_sub": "Get help and resolve issues",
      "about_app": "About App",
      "about_app_sub": "Version info and policies",
      "notifications": "Notifications",
      "notifications_sub": "Manage app notifications",
      "language": "Language",
      "language_sub": "Choose your preferred language",
      "logout_message": "Are you sure you want to log out?",
      "confirm_logout": "Log Out",
      'pleaseinsertname': 'Please enter your name',
      'updateprofile': 'Update Profile Successfully!',
      'profiledetails': 'Profile Details',
      'displayname': 'Display Name',
      "secure_account": "Secure Your Account",
      "secure_account_desc":
          "Update your password to keep your account safe and secure",
      "current_password": "Current Password",
      "current_password_hint": "Enter your current password",
      "current_password_error": "Please enter your current password",
      "new_password": "New Password",
      "new_password_hint": "Enter your new password",
      "new_password_error": "Password must be at least 6 characters long",
      "confirm_new_password": "Confirm New Password",
      "confirm_new_password_hint": "Re-enter your new password",
      "confirm_password_error": "Passwords do not match",
      "password_tips": "Password Tips",
      "tip_length": "Use at least 8 characters",
      "tip_symbols": "Include numbers and symbols",
      "tip_case": "Mix uppercase and lowercase letters",
      "update_password": "Update Password",
      "success_title": "Message Sent!",
      "success_message":
          "Thank you for contacting us. We will reply as soon as possible.",
      "send_new_message": "Send New Message",
      "form_header_title": "We value your feedback",
      "form_header_subtitle":
          "If you have any issues or suggestions, please fill out the form below",
      "name": "Name",
      "name_hint": "Enter your name",
      "name_error": "Please enter your name",
      "email_hint": "Enter your email",
      "email_error": "Please enter your email",
      "email_invalid": "Invalid email format",
      "message": "Message",
      "message_hint": "Describe your issue or suggestion...",
      "message_error": "Please enter a message",
      "message_min": "Message must be at least 10 characters long",
      "sending": "Sending...",
      "send_message": "Send Message",
      "contact_info": "We will reply within 24 hours",
      "send_error": "Failed to send message, please try again",
      "version": "Version : 1.0.0",
      "about_app_desc":
          "This app helps you manage tasks, track progress, and analyze productivity with AI-powered insights.",
      'languageheader': 'Select Language',
      "jan": "Jan",
      "feb": "Feb",
      "mar": "Mar",
      "apr": "Apr",
      "may": "May",
      "jun": "Jun",
      "jul": "Jul",
      "aug": "Aug",
      "sep": "Sep",
      "oct": "Oct",
      "nov": "Nov",
      "dec": "Dec",
      "form_info_text":
          "Your feedback helps us improve the app and provide a better experience.",
      'taskview': 'View Task Details',
      'edit': 'Edit',
      'welcometext':
          'Welcome to AI Task Manager! Organize your tasks efficiently and boost your productivity with our AI-powered features.',
      'overview': 'Overview',
      'taskstatusoverview': 'Task Status Overview',
      'tasksbystatus': 'Tasks By Status',
      'total': 'Total',
      'selectLanguage': 'Select your preferred language',
      'languageDescription': 'Choose a language for the app interface',
      'apply': 'Apply',
      'languageChanged': 'Language changed to {lang}',
      'currentLanguage': 'Current Language',
      'active': 'Active',
      'ready-to-be-productive': 'Ready to be productive',
      'good-morning': 'Good morning',
      'good-afternoon': 'Good afternoon',
      'good-evening': 'Good evening',
      'active-tasks': 'Active Tasks',
      'completion-rate': 'Completion Rate',
      'streak-days': 'Streak Days',
      'view-overview': 'View overview',
      'manage-tasks': 'Manage tasks',
      'ai-assistance': 'AI Assistance',
      'track-progress': 'Track progress',
      'trackProgress': 'Track your progress',
      'today': 'Today',
      'thisWeek': 'This Week',
      'thisMonth': 'This Month',
      'allTime': 'All Time',
      'noDataYet': 'No Data Yet',
      'createTasksToSeeAnalytics': 'Create some tasks to see analytics',
      'allTasks': 'All Tasks',
      'inProgress': 'In Progress',
      'urgent': 'Urgent',
      'now': 'Now',
      'performance': 'Performance',
      'productivity': 'Productivity',
      'onTimeRate': 'On-Time Rate',
      'taskDistribution': 'Task Distribution',
      'weeklyTrend': 'Weekly Trend',
      'insights': 'Insights',
      'noInsightsYet': 'No insights available yet',
      'excellentWork': 'Excellent Work!',
      'keepUpGoodWork':
          'Keep up the good work! Your productivity is outstanding.',
      'goodProgress': 'Good Progress',
      'roomForImprovement':
          'You\'re doing well, but there\'s room for improvement.',
      'needsFocus': 'Needs Focus',
      'tryToCompleteMore':
          'Try to complete more tasks to improve productivity.',
      'overdueTasks': 'Overdue Tasks',
      'focusTip': 'Focus Tip',
      'considerFewTasks': 'Consider focusing on fewer tasks at once.',
      'highActivity': 'High Activity',
      'veryProductive': 'You\'re very productive this week!',
      'warning': 'Warning!',
      'tasksNeedAttention': '@count tasks need attention',
      'appName': 'AI Task Manager',
      'appSubtitle': 'Smart. Simple. Efficient.',
      'initializing': 'Initializing...',
      'loginTitle': 'Log in',
      'testUser1': 'Test User 1',
      'testUser2': 'Test User 2',
      'noAccount': "Don't have an account? ",
      'chooseLanguage': 'Choose language',
      'createAccountHeader': 'Create Account',
      'registerTitle': 'Register',
      'fullName': 'Full Name',
      'registerButton': 'Register',
      'alreadyHaveAccount': 'Already have an account? ',
      'backToLogin': 'Back to Login',
      'hiUser': 'HI, @name 👋',
      'chooseAvatar': 'Choose Avatar',
      'subTitleTaskList': 'Manage your tasks efficentle',
      "aiTaskGenerator": "AI Task Generator",
      "aiTaskGeneratorSubtitle":
          "Turn text into a Task with auto-generated Sub-tasks",
      "textToConvert": "Text to convert",
      "pasteTextPlaceholder":
          "Paste meeting notes, emails, or any text to convert into tasks...",
      "processingWithAI": "Processing with AI...",
      "generateWithAI": "Generate with AI",
      "mainTaskInfo": "Main Task Info",
      "taskName": "Task Name",
      "setMainTaskName": "Set a main task name",
      "start": "Start",
      "end": "End",
      "subtask": "Sub-task",
      "noTaskName": "No task name",
      "noDetails": "No details",
      "subtasksAppearHere": "Sub-tasks will appear here",
      "typeAndGenerate": "Enter text and tap Generate",
      "saveMainTask": "Save Main Task",
      "pleaseEnterText": "Please enter some text",
      "noSubtasksFound": "No sub-tasks could be parsed",
      "aiError": "AI error",
      "pleaseEnterMainTaskName": "Please enter a main task name",
      "cannotSaveTask": "Unable to save the task",
      "savedMainTaskWithNSubtasks":
          "Saved main task with {{count}} sub-tasks ✓",
      'createyourtask' : 'Create your task',    
    },
  };

  // โหลดค่า locale จาก storage
  Locale? getSavedLocale() {
    final String? langCode = _box.read(_storageKey);
    if (langCode != null) {
      return _getLocaleFromString(langCode);
    }
    return null;
  }

  // เปลี่ยนภาษา + บันทึกค่า
  void changeLocale(String languageCode) {
    final locale = _getLocaleFromString(languageCode);
    currentLocale.value = locale;
    Get.updateLocale(locale);
    _box.write(_storageKey, languageCode); // << บันทึก
  }

  // Helper แปลง string → Locale
  Locale _getLocaleFromString(String lang) {
    switch (lang) {
      case 'th_TH':
        return const Locale('th', 'TH');
      case 'en_US':
        return const Locale('en', 'US');
      default:
        return fallbackLocale;
    }
  }
}
