// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3D0DYacneehD9HQS8_5OZDbJuTBvCB4',
    appId: '1:81033975177:web:6a912315efeecc9cb4bd58',
    messagingSenderId: '81033975177',
    projectId: 'ai-task-project-manager',
    authDomain: 'ai-task-project-manager.firebaseapp.com',
    storageBucket: 'ai-task-project-manager.firebasestorage.app',
    measurementId: 'G-N9RB8DNFZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJUTcRsXFhF7cNXWa9koGR4pY3DhBINY',
    appId: '1:81033975177:android:c4e434559f382738b4bd58',
    messagingSenderId: '81033975177',
    projectId: 'ai-task-project-manager',
    storageBucket: 'ai-task-project-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKpyAdfNZ-YyNugW3Dm_BjshpNSQqobe0',
    appId: '1:81033975177:ios:1faa7cb4caa4bf3db4bd58',
    messagingSenderId: '81033975177',
    projectId: 'ai-task-project-manager',
    storageBucket: 'ai-task-project-manager.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKpyAdfNZ-YyNugW3Dm_BjshpNSQqobe0',
    appId: '1:81033975177:ios:1faa7cb4caa4bf3db4bd58',
    messagingSenderId: '81033975177',
    projectId: 'ai-task-project-manager',
    storageBucket: 'ai-task-project-manager.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw3D0DYacneehD9HQS8_5OZDbJuTBvCB4',
    appId: '1:81033975177:web:0a617b9a98e6ac34b4bd58',
    messagingSenderId: '81033975177',
    projectId: 'ai-task-project-manager',
    authDomain: 'ai-task-project-manager.firebaseapp.com',
    storageBucket: 'ai-task-project-manager.firebasestorage.app',
    measurementId: 'G-1TVDG8WPME',
  );
}
